services:
  # === Discovery Service ===
  discovery-server:
    build: ./eurekaserver
    ports:
      - "8761:8761"

  # === Gateway Service ===
  api-gateway:
    build: ./apigateway
    ports:
      - "8080:8888"
    depends_on:
      - user-service
      - product-service
      - discovery-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"

  # === User Service ===
  user-db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Host:Container
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_USER: postgres
      POSTGRES_DB: userdb
    volumes:
      - user-db-volume:/var/lib/postgresql/data

  user-service:
    build: ./user-service-api
    ports:
      - "8082:8082"
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changemeinprod!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  # === Product Service ===
  product-db:
    image: postgres:latest
    ports:
      - "5433:5432"  # Host:Container - Note: inside container still uses default 5432
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_USER: postgres
      POSTGRES_DB: productdb
    volumes:
      - product-db-volume:/var/lib/postgresql/data


  product-service:
    build: ./product-service-api
    ports:
      - "8081:8081"
    depends_on:
      - product-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changemeinprod!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

volumes:
  user-db-volume:
  product-db-volume: