services:
  # === Discovery Service ===
  discovery-server:
    build:
      context: ../discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  # === User Service ===
  user-db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Host:Container
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_USER: postgres
      POSTGRES_DB: userdb
    volumes:
      - user-db-volume:/var/lib/postgresql/data

  user-service:
    build: ./user-service-api
    ports:
      - "8081:8081"
    depends_on:
      - user-db
      - discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changemeinprod!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # === Product Service ===
  product-db:
    image: postgres:latest
    ports:
      - "5433:5432"  # Host:Container - Note: inside container still uses default 5432
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_USER: postgres
      POSTGRES_DB: productdb
    volumes:
      - product-db-volume:/var/lib/postgresql/data


  product-service:
    build: ./product-service-api
    ports:
      - "8082:8082"
    depends_on:
      - product-db
      - discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changemeinprod!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  user-db-volume:
  product-db-volume: